core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud.urls')),
]

crud/urls.py
from django.urls import path
from .views import home, vehicle_details, update_details, edit_details, delete_details

urlpatterns = [
    path('', home, name="home"),    # list page
    path('vehicle/<str:id>/', vehicle_details, name="vehicle_details"), # details page
    path('update/', update_details, name="update_details"), # update page
    path('edit/<str:id>/', edit_details, name="edit_details"),
    path('delete/<str:id>/', delete_details, name="delete_details"),
]

crud/models.py
from django.db import models
import uuid
from django.core.validators import MaxValueValidator

# Create your models here.

class Vehicle(models.Model):
    """
    Model for Vehicle
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=150)
    location = models.CharField(max_length=250)
    speed = models.DecimalField(max_digits=6, decimal_places=3)
    avg_speed = models.DecimalField(max_digits=6, decimal_places=3, default=000.000)
    temperature = models.DecimalField(max_digits=5, decimal_places=2)
    fuel_level = models.PositiveIntegerField(validators=[MaxValueValidator(100)])
    engine_status = models.CharField(max_length=250)
    camera1 = models.CharField(max_length=250, blank=True)
    camera2 = models.CharField(max_length=250, blank=True)
    active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} - {self.id}"

crud/forms.py
from django import forms
from django.forms.widgets import CheckboxInput
from .models import Vehicle

class VehicleCreateForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        fields = ["name", "location", "speed", "avg_speed", "temperature",
                  "fuel_level", "engine_status", "camera1", "camera2", "active"]

    def __init__(self, *args, **kwargs):
        super(VehicleCreateForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if not visible.field.widget.__class__.__name__ == CheckboxInput().__class__.__name__:
                visible.field.widget.attrs['class'] = 'form-control'
            # print(visible)

class VehicleUpdateForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        fields = ["name", "location", "speed", "avg_speed", "temperature",
                  "fuel_level", "engine_status", "camera1", "camera2", "active"]

    def __init__(self, *args, **kwargs):
        super(VehicleUpdateForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            # print(visible)
            if not visible.field.widget.__class__.__name__ == CheckboxInput().__class__.__name__:
                visible.field.widget.attrs['class'] = 'form-control'

crud/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Vehicle
from .forms import VehicleCreateForm, VehicleUpdateForm
from django.contrib import messages

# Create your views here.

def home(request):
    """
    Home Page that displays all vehicles in table form
    """
    all_vehicles = Vehicle.objects.all()
    context = {
        "all_vehicles": all_vehicles
    }
    return render(request, "crud/home.html", context)


def vehicle_details(request, id):
    """
    Vehicle details page
    """
    vehicle = get_object_or_404(Vehicle, id=id)
    context = {
        "vehicle": vehicle
    }
    return render(request, "crud/vehicle_details.html", context)


def update_details(request):
    """
    Add or Update vehicles
    """
    all_vehicles = Vehicle.objects.all()
    if request.method == 'POST':
        add_form = VehicleCreateForm(request.POST or None)
        if add_form.is_valid():
            add_form.save()
            messages.success(request, f"Your vehicle details has been saved!")
            return redirect('update_details')
    else:
        add_form = VehicleCreateForm()

    context = {
        'all_vehicles': all_vehicles,
        'add_form': add_form,
    }

    return render(request, 'crud/update_details.html', context)


def edit_details(request, id):
    """
    Handles editing of vehicle details 
    """
    if request.method == 'POST':
        instance = get_object_or_404(Vehicle, id=id)
        update_form = VehicleUpdateForm(request.POST, instance=instance)
        if update_form.is_valid():
            update_form.save()
            messages.success(request, f"Your vehicle details has been updated!")
        else:
            messages.error(request, f"Update failed!")
    return redirect('update_details')


def delete_details(request, id):
    """ 
    Handles deletion of a vehicle from db
    """
    try:
        vehicle = get_object_or_404(Vehicle, id=id)
        vehicle.delete()
        messages.success(request, f"Deletion Successful!")
    except Exception as e:
        messages.error(request, f"Deletion Failed!\n{e}")
    return redirect('home')

templates/crud/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta name="description" content="car,vehicle,automobile,siteguide">

		<!-- CSS -->
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
			crossorigin="anonymous"
		/>
		<link
			rel="stylesheet"
			href="https://cdn.jsdelivr.net/npm/boxicons@2.0.9/css/boxicons.min.css"
		/>
		<link rel="stylesheet" href="{% static 'core/css/main.css' %}" />

		<title>{% block title %}{% endblock %}</title>
	</head>
	<body id="body-pd">

        <!-- Header -->
		<header class="header" id="header">
			<div class="header_toggle">
				<i class="bx bx-menu" id="header-toggle"></i>
			</div>
			<div class="header_img">
				<img
					src="https://avatars.githubusercontent.com/u/64803043?v=4"
					alt="avatar"
				/>
			</div>
		</header>

        <!-- SideNav -->
		<div class="l-navbar" id="nav-bar">
			<nav class="nav">
				<div>
					<a href="{% url 'home' %}" class="nav_logo">
						<i class="bx bxs-car nav_logo-icon"></i>
						<span class="nav_logo-name">SiteGuide</span>
					</a>
					<div class="nav_list">
						<a href="{% url 'home' %}" class="nav_link {% block home %}{% endblock %}">
							<i class="bx bx-list-ul nav_icon"></i>
							<span class="nav_name">All Vehicles</span>
						</a>
						<a href="{% url 'update_details' %}" class="nav_link {% block update %}{% endblock %}">
							<i class="bx bx-add-to-queue nav_icon"></i>
							<span class="nav_name">Add / Update</span>
						</a>
					</div>
				</div>
			</nav>
		</div>

		<!-- Messages -->
		{% if messages %}
		<div class="msgmessages container">
			{% for message in messages %}
			<div class="alert {% if message.tags %} alert-{{message.tags}} {% else %} alert-primary {% endif %}">
				{{ message }}
			</div>
			{% endfor %}
		</div>
		{% endif %}

        <!-- Content Block -->
		<div class="height-100">
		    {% block content %}{% endblock %}
		</div>

		<!-- JavaScript -->
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
			crossorigin="anonymous"
		></script>
		<script src="{% static 'core/js/index.js' %}"></script>
	</body>
</html>

templates/crud/home.html
{% extends "crud/base.html" %}
{% load static %}

{% block title %}
    All Vehicles
{% endblock %}

{% block home %}active{% endblock %}

{% block content %}
<div class="container">
<div class="table-responsive">
<table class="table table-hover table-bordered text-center table-responsive">
    <thead style="background-color: #8A21CF; color: #fff;">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Location</th>
        <th scope="col">Speed</th>
        <th scope="col">Avg Speed</th>
        <th scope="col">Temperature (C)</th>
        <th scope="col">Fuel Level</th>
        <th scope="col">Engine Status</th>
        <th scope="col">Active</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
        {% for vehicle in all_vehicles %}
        <tr>
            <th scope="row">{{vehicle.name}}</th>
            <td>{{vehicle.location}}</td>
            <td>{{vehicle.speed}}</td>
            <td>{{vehicle.avg_speed}}</td>
            <td>{{vehicle.temperature}}</td>
            <td>{{vehicle.fuel_level}}%</td>
            <td>{{vehicle.engine_status}}</td>
            <td>
                {% if vehicle.active %}
                    ON
                {% else %}
                    OFF
                {% endif %}
            </td>
            <td class="d-flex justify-content-center align-items-center">
                <a href="{% url 'vehicle_details' vehicle.id %}"  class="m-1 btn2 btn-primary"><i class='bx bxs-share'></i></a>
                <a href="{% url 'update_details' %}#{{vehicle.id}}" class="m-1 btn2 btn-warning"><i class='bx bx-pencil'></i></a>
                <a href="{% url 'delete_details' vehicle.id %}" class="m-1 btn2 btn-danger"><i class='bx bx-trash'></i></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
</div>
{% endblock %}

templates/crud/update_details.html
{% extends "crud/base.html" %}
{% load static %}

{% block title %}
    Add or Update details
{% endblock %}

{% block update %}active{% endblock %}

{% block content %}
<ul class="nav switch-nav nav-tabs mb-4" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#create" type="button" role="tab" aria-controls="home" aria-selected="true">Add Vehicle</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#update" type="button" role="tab" aria-controls="profile" aria-selected="false">Update Vehicle</button>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="create" role="tabpanel" aria-labelledby="home-tab">
        <form class="container form-group" method="post">
            {% csrf_token %}
            {{add_form.as_p}}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <div class="tab-pane fade" id="update" role="tabpanel" aria-labelledby="profile-tab">
        <div class="accordion accordion-flush" id="accordionFlushExample">
            {% for vehicle in all_vehicles %}
                <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingOne">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#tg{{forloop.counter}}" aria-expanded="false" aria-controls="flush-collapseOne">
                        {{vehicle.name}}
                        </button>
                    </h2>
                    <div id="tg{{forloop.counter}}" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body">
                            <form class="form-group" method="post" action="{% url 'edit_details' vehicle.id %}">
                                {% csrf_token %}
                                <p>
                                    <label for="id_name">Name</label>
                                    <input value="{{vehicle.name}}" type="text" name="name" maxlength="150" class="form-control" required id="id_name">
                                </p>
                                
                                <p>
                                    <label for="id_location">Location</label>
                                    <input value="{{vehicle.location}}" type="text" name="location" maxlength="250" class="form-control" required id="id_location">
                                </p>
                                <p>
                                    <label for="id_speed">Speed</label>
                                    <input value="{{vehicle.speed}}" type="number" name="speed" step="0.001" class="form-control" required id="id_speed">
                                </p>
                                <p>
                                    <label for="id_avg_speed">Avg speed</label>
                                    <input type="number" name="avg_speed" value="{{vehicle.avg_speed}}" step="0.001" class="form-control" required id="id_avg_speed">
                                </p>
                                <p>
                                    <label for="id_temperature">Temperature</label>
                                    <input value="{{vehicle.temperature}}" type="number" name="temperature" step="0.01" class="form-control" required id="id_temperature">
                                </p>
                                <p>
                                    <label for="id_fuel_level">Fuel level</label>
                                    <input value="{{vehicle.fuel_level}}" type="number" name="fuel_level" min="0" class="form-control" required id="id_fuel_level">
                                </p>
                                <p>
                                    <label for="id_engine_status">Engine status</label>
                                    <input value="{{vehicle.engine_status}}" type="text" name="engine_status" maxlength="250" class="form-control" required id="id_engine_status">   
                                </p>
                                <p>
                                    <label for="id_camera1">Camera1</label>
                                    <input value="{{vehicle.camera1}}" type="text" name="camera1" maxlength="250" class="form-control" id="id_camera1">
                                </p>
                                <p>
                                    <label for="id_camera2">Camera2</label>
                                    <input value="{{vehicle.camera2}}" type="text" name="camera2" maxlength="250" class="form-control" id="id_camera2">
                                </p>
                                <p>
                                    <label for="id_active">Active</label>
                                    <input type="checkbox" name="active" id="id_active" {% if vehicle.active %} checked {% endif %}>
                                </p>
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <br>
                            </form>
                        </div>
                    </div>
                </div>
            {% endfor %}
            
          </div>
    </div>
  </div>


    
{% endblock %}

templates/crud/vehicle_details.html
{% extends "crud/base.html" %}
{% load static %}

{% block title %}
    Vehicle Details
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8">
            <div class="d-flex flex-row bd-highlight mb-3">
                <div class="p-2 bd-highlight">
                    <div style="border: 3px solid rgb(183, 0, 255);" class="header_img">
                        <img
                            src="https://avatars.githubusercontent.com/u/64803043?v=4"
                            alt="avatar"
                        />
                    </div>
                </div>
                <div class="p-2 bd-highlight">
                    <a href="#" class="btn btn-primary  d-flex align-items-center justify-content-center">Camera 1</a>
                </div>
                <div class="p-2 bd-highlight">
                    <a href="#" class="btn btn-warning d-flex align-items-center justify-content-center">Camera 2</a>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="d-flex flex-row-reverse bd-highlight">
                {% if vehicle.active %}
                    <div class="p-2 bd-highlight">
                        <button type="button" class="btn btn-success">ON</button>
                    </div>
                    <div class="p-2 bd-highlight">
                        <button type="button" class="btn btn-outline-danger">OFF</button>
                    </div>
                {% else %}
                    <div class="p-2 bd-highlight">
                        <button type="button" class="btn btn-outline-success">ON</button>
                    </div>
                    <div class="p-2 bd-highlight">
                        <button type="button" class="btn btn-danger">OFF</button>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-8">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d471220.5630409112!2d88.04953608529773!3d22.675752093263746!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39f882db4908f667%3A0x43e330e68f6c2cbc!2sKolkata%2C%20West%20Bengal!5e0!3m2!1sen!2sin!4v1629893750616!5m2!1sen!2sin" width="100%" height="290" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>
        <div class="col-4 d-flex flex-column">
            <div style="height: 45%;" class="card mb-2">
                <div class="card-body">
                  <h5 class="card-title"><em>Speed</em></h5>
                  <h3 class="card-text">{{vehicle.speed}} KMPH</h3>
                </div>
            </div>
            <div style="height: 45%;" class="card mt-2">
                <div class="card-body">
                  <h5 class="card-title"><em>Average Speed</em></h5>
                  <h3 class="card-text">{{vehicle.avg_speed}} KMPH</h3>
                </div>
            </div>            
        </div>
    </div>
    <div class="row mt-2">
        <div class="card-cont col-sm">
            <div style="height: 145%;" class="card">
                <div class="card-body">
                  <h5 class="card-title"><em>Engine Status</em></h5>
                  <h3 class="card-text">{{vehicle.engine_status}}</h3>
                </div>
            </div>
        </div>
        <div class="card-cont col-sm">
            <div style="height: 145%;" class="card">
                <div class="card-body">
                  <h5 class="card-title"><em>Fuel Level</em></h5>
                  <h3 class="card-text">{{vehicle.fuel_level}} %</h3>
                </div>
            </div>
        </div>
        <div class="card-cont col-sm">
            <div style="height: 145%;" class="card">
                <div class="card-body">
                  <h5 class="card-title"><em>Temperature</em></h5>
                  <h3 class="card-text">{{vehicle.temperature}} °C</h3>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}